name: AI Generated Meta-Feedback (Teacher Trigger)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for triggering (optional)"
        required: false
        default: "class-selected-run"

permissions:
  contents: write
  actions: read
  checks: read

concurrency:
  group: "meta-feedback-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  meta_feedback:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Guard: only teacher can trigger
        run: |
          ALLOWED_ACTORS="Ruixi1313"
          if ! echo "$ALLOWED_ACTORS" | tr ' ' '\n' | grep -q "^${GITHUB_ACTOR}$"; then
            echo "Only teachers can run this workflow. Actor: ${GITHUB_ACTOR}"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate meta-feedback with GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }} # optional (proxy/Azure)
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}           # e.g., gpt-4o-mini
        run: |
          python scripts/generate_feedback.py

      - name: Commit & push feedback
        run: |
          git config user.email "meta-feedback-bot@users.noreply.github.com"
          git config user.name "Meta-Feedback Bot"
          git add Meta-Feedback_*.md .meta-feedback/state.json || true
          git commit -m "Teacher-triggered meta-feedback" || echo "No changes to commit"
          git push || true
